[package]
name = "gpui-rsc"
version = "0.1.0"
edition = "2024"

[dependencies]
scraper = { version = "0.24", optional = true }
syn = { version = "2", features = ["full", "visit-mut"], optional = true }
quote = { version = "1", optional = true }
toml = { version = "0.8", optional = true }

[features]
default = ["compiler"]
compiler = ["dep:scraper", "dep:syn", "dep:quote", "dep:toml"]
debug-fps = []

[[bin]]
name = "gpui-rsc"
path = "src/main.rs"
required-features = ["compiler"]
